cc_library(
    name = "line_segment",
    hdrs = ["line_segment.h"],
    srcs = ["line_segment.cc"],
    deps = ["@eigen",
            "@com_google_googletest//:gtest_main"],
)

# cc_binary(
#     name = "hello-world",
#     srcs = ["hello-world.cc"],
#     deps = [
#         ":hello-greet",
#         "//lib:hello-time",
#     ],
# )