name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: run
        uses: ngalaiko/bazel-action/1.2.1@master
        with:
          args: bazel test //...